# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Kirk's spot
author: Kirk Bonney
description: Not another rambling blog

show_excerpts: true
use_math: true
google_analytics:


email: kirkb1998@gmail.com
github_username: kbonney
instagram_username: kerpography

# Set headers
header_pages:
 - pages/about.md
 - index.md
 - pages/formal-writing.md
 - pages/photos.md
 - pages/music.md
 
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-photo-gallery

remote_theme: kbonney/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - /assets/images/ #Set to location of photos